#!/bin/sh
HOME=/; export HOME
PATH=/bin:/sbin; export PATH
echo /etc/rc started                                    >/dev/console 2>&1
echo to stdout
date                                                    >/dev/console 2>&1
exit 0
